### PR TITLE
Force virtualenv==15.0.2 in all platforms

### PR DESCRIPTION
**Pull request by hltbra**
Tested in staging with 14.04 and it worked to upgrade and from scratch.

cc @spulec, @andrewgross, @mateusdelbianco

### CODE REVIEW

**Comment by spulec** [comment]
:+1:

**Comment by andrewgross** [comment]
+1  I should probably start using more modern versions of virtualenv and
pip in my local too huh.

On Thu, Jul 14, 2016 at 1:38 PM, Steve Pulec <notifications@github.com>
wrote:

> 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yipit-cookbooks/python/pull/2#issuecomment-232737126>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAWlxv2i2xYFaG06FZK0yOeWGr6k8Y2Qks5qVnQogaJpZM4JMpZ9>
> .
>

-- 
New: *UA, Brand Insights: China, IMAX, Hotels (H, HLT, HOT, MAR)*
Portfolio: *Airbnb, AN, Asset Managers, AWAY, BABA, CPRT, EBAY, ETSY, EXPE, 
FB: Instagram, GRPN, JD, KMX, LC, LULU, MELI, NOW, PCLN, Prosper, PYPL, 
SLCY, TRIP, TWTR, VEEV, VIPS, W, WDAY, ZG*
yipitdata.com | Analyzing web data for institutional investors

Any information or data conveyed in this communication is intended for 
informational purposes only. It cannot be relied on in any manner as, 
legal, tax or investment advice. Nor is anything contained herein or in 
connection therewith intended to be used as the primary basis of investment 
decisions or predictive of the movement of the market prices of any 
securities. Please refer to additional disclosures in our reports.

**Comment by hltbra** [comment]
@andrewgross: good idea. we can even force that in yy, can't we?

**Comment by andrewgross** [comment]
i think so.  Right now it just calls pip and mkvirtualenv, but we could
have upgrade steps.

On Thu, Jul 14, 2016 at 1:49 PM, Hugo Lopes Tavares <
notifications@github.com> wrote:

> @andrewgross <https://github.com/andrewgross>: good idea. we can even
> force that in yy, can't we?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yipit-cookbooks/python/pull/2#issuecomment-232740129>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAWlxh0psJKGlgerXpMW0XlMwD3VqV_yks5qVnalgaJpZM4JMpZ9>
> .
>

-- 
New: *UA, Brand Insights: China, IMAX, Hotels (H, HLT, HOT, MAR)*
Portfolio: *Airbnb, AN, Asset Managers, AWAY, BABA, CPRT, EBAY, ETSY, EXPE, 
FB: Instagram, GRPN, JD, KMX, LC, LULU, MELI, NOW, PCLN, Prosper, PYPL, 
SLCY, TRIP, TWTR, VEEV, VIPS, W, WDAY, ZG*
yipitdata.com | Analyzing web data for institutional investors

Any information or data conveyed in this communication is intended for 
informational purposes only. It cannot be relied on in any manner as, 
legal, tax or investment advice. Nor is anything contained herein or in 
connection therewith intended to be used as the primary basis of investment 
decisions or predictive of the movement of the market prices of any 
securities. Please refer to additional disclosures in our reports.

**Comment by andrewgross** [comment]
We should rewrite yy in golang too

On Thu, Jul 14, 2016 at 2:02 PM, Andrew Gross <andrew@yipitdata.com> wrote:

> i think so.  Right now it just calls pip and mkvirtualenv, but we could
> have upgrade steps.
>
> On Thu, Jul 14, 2016 at 1:49 PM, Hugo Lopes Tavares <
> notifications@github.com> wrote:
>
>> @andrewgross <https://github.com/andrewgross>: good idea. we can even
>> force that in yy, can't we?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/yipit-cookbooks/python/pull/2#issuecomment-232740129>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAWlxh0psJKGlgerXpMW0XlMwD3VqV_yks5qVnalgaJpZM4JMpZ9>
>> .
>>
>
>

-- 
New: *UA, Brand Insights: China, IMAX, Hotels (H, HLT, HOT, MAR)*
Portfolio: *Airbnb, AN, Asset Managers, AWAY, BABA, CPRT, EBAY, ETSY, EXPE, 
FB: Instagram, GRPN, JD, KMX, LC, LULU, MELI, NOW, PCLN, Prosper, PYPL, 
SLCY, TRIP, TWTR, VEEV, VIPS, W, WDAY, ZG*
yipitdata.com | Analyzing web data for institutional investors

Any information or data conveyed in this communication is intended for 
informational purposes only. It cannot be relied on in any manner as, 
legal, tax or investment advice. Nor is anything contained herein or in 
connection therewith intended to be used as the primary basis of investment 
decisions or predictive of the movement of the market prices of any 
securities. Please refer to additional disclosures in our reports.

**Comment by mateusdelbianco** [comment]
I've been using recent versions of virtualenv and pip since I've joined. The only issue I ran into was the package naming problem, which was more a localshop problem than virtualenv/pip themselves.

**Pull request merged**
